[package]
name = "gigd-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
glfw = { version = "0.61.0", features = ["static-link"] }
wgpu = "28.0"
pollster = "0.4.0"
glam = {  version = "0.30.9", features = ["bytemuck", "encase"] }
bytemuck = "1.24.0"
